version: "2"
run:
  tests: false
linters:
  enable:
    - gosec
    - misspell
    - nolintlint
    - revive
  settings:
    misspell:
      locale: US
      ignore-rules:
        - visable
    nolintlint:
      allow-unused: true
    revive:
      rules:
      - name: var-naming
        disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: don't use underscores
      - path: (.+)\.go$
        text: don't use ALL_CAPS
      - path: (.+)\.go$
        text: S1008
      - path: (.+)\.go$
        text: SA4009
      - path: (.+)\.go$
        text: G404
      - path: (.+)\.go$
        text: G401
      - path: (.+)\.go$
        text: G501
      - path: (.+)\.go$
        text: 'indent-error-flow:'
      - path: (.+)\.go$
        text: 'if-return:'
      - path: (.+)\.go$
        text: 'exported:'
      - path: (.+)\.go$
        text: 'unused-parameter: parameter'
      - path: (.+)\.go$
        text: G115
    paths:
      - testinit.go
      - cmsys/fnv_hash.go
      - 00-config.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - testinit.go
      - cmsys/fnv_hash.go
      - 00-config.go
      - third_party$
      - builtin$
      - examples$
