package dbcs

func config() {
	COMMENT_STEP_DIFF_NANO_TS = setNanoTSConfig("COMMENT_STEP_DIFF_NANO_TS", COMMENT_STEP_DIFF_NANO_TS)
	COMMENT_STEP_DIFF2_NANO_TS = setNanoTSConfig("COMMENT_STEP_DIFF2_NANO_TS", COMMENT_STEP_DIFF2_NANO_TS)
}
