package dbcs

import (
	"github.com/Ptt-official-app/pttbbs-backend/schema"
	"github.com/Ptt-official-app/pttbbs-backend/types"
	"github.com/sirupsen/logrus"
)

var (
	testFilename21            = "temp15"
	testContentAll21          []byte
	testContent21             []byte
	testSignature21           []byte
	testComment21             []byte
	testFirstCommentsDBCS21   []byte
	testTheRestCommentsDBCS21 []byte
	testContent21Big5         [][]*types.Rune
	testContent21Utf8         [][]*types.Rune

	testFirstComments21       []*schema.Comment
	testFullFirstComments21   []*schema.Comment
	testTheRestComments21     []*schema.Comment
	testFullTheRestComments21 []*schema.Comment
)

func initTest21() {
	testContentAll21, testContent21, testSignature21, testComment21, testFirstCommentsDBCS21, testTheRestCommentsDBCS21 = loadTest(testFilename21)

	logrus.Infof("initTest21: after loadTest: testContentAll21: %v testContent21: %v testSignature21: %v", len(testContentAll21), len(testContent21), len(testSignature21))

	testContent21Big5 = [][]*types.Rune{}

	testContent21Utf8 = [][]*types.Rune{
		{ // 0
		},
		{ // 1
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "███◣ ███◣  ███◣  ███◣",
				Big5:   []byte("\xa2i\xa2i\xa2i\xa2\xa9 \xa2i\xa2i\xa2i\xa2\xa9  \xa2i\xa2i\xa2i\xa2\xa9  \xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2i\xa2\xa9 \xa2i\xa2i\xa2i\xa2\xa9  \xa2i\xa2i\xa2i\xa2\xa9  \xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   "",
				Big5:   nil,
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 2
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte(" "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},

				DBCS: []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "███ ",
				Big5:   []byte("\xa2i\xa2i\xa2i "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},

				DBCS: []byte("\x1b[1m\xa2i\xa2i\xa2i "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i"),
			},
			{
				Utf8:   "███  ",
				Big5:   []byte("\xa2i\xa2i\xa2i  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i  "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "███  ",
				Big5:   []byte("\xa2i\xa2i\xa2i  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i  "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 3
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte(" "),
			},
			{
				Utf8:   "█◣",
				Big5:   []byte("\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2\xa9"),
			},
			{
				Utf8:   "█   ",
				Big5:   []byte("\xa2i   "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i   "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i"),
			},
			{
				Utf8:   "█▆█  ",
				Big5:   []byte("\xa2i\xa2g\xa2i  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2g\xa2i  "),
			},
			{
				Utf8:   "◣",
				Big5:   []byte("\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xa9"),
			},
			{
				Utf8:   "◢█◤  ",
				Big5:   []byte("\xa2\xa8\xa2i\xa2\xab  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2\xa8\xa2i\xa2\xab  "),
			},
			{
				Utf8:   "◣",
				Big5:   []byte("\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xa9"),
			},
			{
				Utf8:   "◢█◤",
				Big5:   []byte("\xa2\xa8\xa2i\xa2\xab"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2\xa8\xa2i\xa2\xab"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 4
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte(" "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "██   ",
				Big5:   []byte("\xa2i\xa2i   "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i   "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "█  █  ",
				Big5:   []byte("\xa2i  \xa2i  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i  \xa2i  "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "███  ",
				Big5:   []byte("\xa2i\xa2i\xa2i  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i  "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 5
			{
				Utf8:   "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▃▃▃▃▂▂▂▁▁",
				Big5:   []byte("\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2d\xa2d\xa2d\xa2d\xa2c\xa2c\xa2c\xa2b\xa2b"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2d\xa2d\xa2d\xa2d\xa2c\xa2c\xa2c\xa2b\xa2b"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 6
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 7
			{
				Utf8:   "                         ",
				Big5:   []byte("                         "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("                         "),
			},
			{
				Utf8:   "☆  NBA TODAY  1/8 2023  ★",
				Big5:   []byte("\xa1\xb8  NBA TODAY  1/8 2023  \xa1\xb9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_RED, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_RED, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;31m\xa1\xb8  NBA TODAY  1/8 2023  \xa1\xb9"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 8
			{
				Utf8:   "        ",
				Big5:   []byte("        "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("        "),
			},
			{
				Utf8:   "Starting Lineup                               ",
				Big5:   []byte("Starting Lineup                               "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLACK, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLACK, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;30mStarting Lineup                               "),
			},
			{
				Utf8:   "Starting Lineup",
				Big5:   []byte("Starting Lineup"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[33mStarting Lineup"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 9
			{
				Utf8:   "      ",
				Big5:   []byte("      "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("      "),
			},
			{
				Utf8:   "══════════                          ══════════",
				Big5:   []byte("\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9                          \xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9                          \xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 10
			{
				Utf8:   "      ",
				Big5:   []byte("      "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("      "),
			},
			{
				Utf8:   "#23  L. Markkanen       ",
				Big5:   []byte("#23  L. Markkanen       "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m#23  L. Markkanen       "),
			},
			{
				Utf8:   "█◣◥◣ ███◣     ",
				Big5:   []byte("\xa2i\xa2\xa9\xa2\xaa\xa2\xa9 \xa2i\xa2i\xa2i\xa2\xa9     "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i\xa2\xa9\xa2\xaa\xa2\xa9 \xa2i\xa2i\xa2i\xa2\xa9     "),
			},
			{
				Utf8:   "#24  D. Brooks          ",
				Big5:   []byte("#24  D. Brooks          "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;37m#24  D. Brooks          "),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 11
			{
				Utf8:   "      ",
				Big5:   []byte("      "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("      "),
			},
			{
				Utf8:   "#41  K. Olynyk          ",
				Big5:   []byte("#41  K. Olynyk          "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m#41  K. Olynyk          "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i"),
			},
			{
				Utf8:   "█  █ ",
				Big5:   []byte("\xa2i  \xa2i "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i  \xa2i "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i"),
			},
			{
				Utf8:   "███     ",
				Big5:   []byte("\xa2i\xa2i\xa2i     "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i     "),
			},
			{
				Utf8:   "#13  J. Jackson Jr.     ",
				Big5:   []byte("#13  J. Jackson Jr.     "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[37m#13  J. Jackson Jr.     "),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 12
			{
				Utf8:   "      ",
				Big5:   []byte("      "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("      "),
			},
			{
				Utf8:   "#8   J. Vanderbilt      ",
				Big5:   []byte("#8   J. Vanderbilt      "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m#8   J. Vanderbilt      "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i"),
			},
			{
				Utf8:   "◣",
				Big5:   []byte("\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xa9"),
			},
			{
				Utf8:   "█ ",
				Big5:   []byte("\xa2i "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i"),
			},
			{
				Utf8:   "█▆▆     ",
				Big5:   []byte("\xa2i\xa2g\xa2g     "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2g\xa2g     "),
			},
			{
				Utf8:   "#2   X. Tillman         ",
				Big5:   []byte("#2   X. Tillman         "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[37m#2   X. Tillman         "),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 13
			{
				Utf8:   "      ",
				Big5:   []byte("      "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("      "),
			},
			{
				Utf8:   "###  J. Clarkson          ",
				Big5:   []byte("###  J. Clarkson          "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m###  J. Clarkson          "),
			},
			{
				Utf8:   "◥█◤ ",
				Big5:   []byte("\xa2\xaa\xa2i\xa2\xab "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2\xaa\xa2i\xa2\xab "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xaa"),
			},
			{
				Utf8:   "▆▆█     ",
				Big5:   []byte("\xa2g\xa2g\xa2i     "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2g\xa2g\xa2i     "),
			},
			{
				Utf8:   "#22  D. Bane            ",
				Big5:   []byte("#22  D. Bane            "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[37m#22  D. Bane            "),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 14
			{
				Utf8:   "      ",
				Big5:   []byte("      "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("      "),
			},
			{
				Utf8:   "#11  M. Conley                                #21  T. Jones           ",
				Big5:   []byte("#11  M. Conley                                #21  T. Jones           "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m#11  M. Conley                                #21  T. Jones           "),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 15
		},
		{ // 16
			{
				Utf8:   "   ███◣",
				Big5:   []byte("   \xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[m\x1b[34m   \xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "███◣",
				Big5:   []byte("\xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "██◣",
				Big5:   []byte("\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "███◣",
				Big5:   []byte("\xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "███◣",
				Big5:   []byte("\xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█◣    ",
				Big5:   []byte("\xa2i\xa2\xa9    "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2\xa9    "),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "██◣",
				Big5:   []byte("\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "███◣",
				Big5:   []byte("\xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "███◣",
				Big5:   []byte("\xa2i\xa2i\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i\xa2i\xa2i\xa2\xa9"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 17
			{
				Utf8:   "   █",
				Big5:   []byte("   \xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m   \xa2i"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "██",
				Big5:   []byte("\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "█    ",
				Big5:   []byte("\xa2i    "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i    "),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "██",
				Big5:   []byte("\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 18
			{
				Utf8:   "   █",
				Big5:   []byte("   \xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m   \xa2i"),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i"),
			},
			{
				Utf8:   "◣",
				Big5:   []byte("\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2\xa9"),
			},
			{
				Utf8:   "▆",
				Big5:   []byte("\xa2g"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2g"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "█▆█",
				Big5:   []byte("\xa2i\xa2g\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2g\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◣ ",
				Big5:   []byte("\xa2\xa9 "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xa9 "),
			},
			{
				Utf8:   "█ ",
				Big5:   []byte("\xa2i "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i "),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◣",
				Big5:   []byte("\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xa9"),
			},
			{
				Utf8:   "◢█◤",
				Big5:   []byte("\xa2\xa8\xa2i\xa2\xab"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2\xa8\xa2i\xa2\xab"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◣",
				Big5:   []byte("\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xa9"),
			},
			{
				Utf8:   "◢█◤",
				Big5:   []byte("\xa2\xa8\xa2i\xa2\xab"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2\xa8\xa2i\xa2\xab"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i"),
			},
			{
				Utf8:   "█◣",
				Big5:   []byte("\xa2i\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[;34;40m\xa2i\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◣ ",
				Big5:   []byte("\xa2\xa9 "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xa9 "),
			},
			{
				Utf8:   "█ ",
				Big5:   []byte("\xa2i "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i "),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "█▆▆",
				Big5:   []byte("\xa2i\xa2g\xa2g"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2g\xa2g"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "█",
				Big5:   []byte("\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2i"),
			},
			{
				Utf8:   "█▆▆",
				Big5:   []byte("\xa2i\xa2g\xa2g"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2g\xa2g"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 19
			{
				Utf8:   "   ◥",
				Big5:   []byte("   \xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m   \xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "█◥◣",
				Big5:   []byte("\xa2i\xa2\xaa\xa2\xa9"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2\xaa\xa2\xa9"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "██",
				Big5:   []byte("\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "███",
				Big5:   []byte("\xa2i\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "██",
				Big5:   []byte("\xa2i\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2i"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "█▆▆",
				Big5:   []byte("\xa2i\xa2g\xa2g"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2i\xa2g\xa2g"),
			},
			{
				Utf8:   " ",
				Big5:   []byte(" "),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m "),
			},
			{
				Utf8:   "◥",
				Big5:   []byte("\xa2\xaa"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK},
				DBCS:   []byte("\x1b[34m\xa2\xaa"),
			},
			{
				Utf8:   "▆▆█",
				Big5:   []byte("\xa2g\xa2g\xa2i"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1m\xa2g\xa2g\xa2i"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 20
			{
				Utf8:   "▁▁▂▂▂▃▃▃▃▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
				Big5:   []byte("\xa2b\xa2b\xa2c\xa2c\xa2c\xa2d\xa2d\xa2d\xa2d\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2b\xa2b\xa2c\xa2c\xa2c\xa2d\xa2d\xa2d\xa2d\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e\xa2e"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 21

		},
		{ // 22
		},
		{ // 23
			{
				Utf8:   "╭──────────────┬──────────────────────╮",
				Big5:   []byte("\xf9\xfa\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2s\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xf9\xfb"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[m\x1b[1;34m\xf9\xfa\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2s\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xf9\xfb"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 24
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2x"),
			},
			{
				Utf8:   "ARENA STATS                 ",
				Big5:   []byte("ARENA STATS                 "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLUE, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLUE, Highlight: true},
				DBCS:   []byte("\x1b[33;44mARENA STATS                 "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34;40m\xa2x"),
			},
			{
				Utf8:   "Jazz                                        ",
				Big5:   []byte("Jazz                                        "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_MAGENTA, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_MAGENTA, Highlight: true},
				DBCS:   []byte("\x1b[45m\x1b[33mJazz                                        "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34;40m\xa2x"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 25
			{
				Utf8:   "├──────────────┤                  ",
				Big5:   []byte("\xa2u\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2t                  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2u\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2w\xa2t                  "),
			},
			{
				Utf8:   "◢▉    ◢▉     ███▉ ",
				Big5:   []byte("\xa2\xa8\xa2p    \xa2\xa8\xa2p     \xa2i\xa2i\xa2i\xa2p "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[33m\xa2\xa8\xa2p    \xa2\xa8\xa2p     \xa2i\xa2i\xa2i\xa2p "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 26
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2x"),
			},
			{
				Utf8:   "Arena: ",
				Big5:   []byte("Arena: "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[37mArena: "),
			},
			{
				Utf8:   "FedExForum           ",
				Big5:   []byte("FedExForum           "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[36mFedExForum           "),
			},
			{
				Utf8:   "│                  ",
				Big5:   []byte("\xa2x                  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x                  "),
			},
			{
				Utf8:   "  ▉      ▉     ▉    ▉ ",
				Big5:   []byte("  \xa2p      \xa2p     \xa2p    \xa2p "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[33m  \xa2p      \xa2p     \xa2p    \xa2p "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 27
			{
				Utf8:   "│       ",
				Big5:   []byte("\xa2x       "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2x       "),
			},
			{
				Utf8:   "Memphis              ",
				Big5:   []byte("Memphis              "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[36mMemphis              "),
			},
			{
				Utf8:   "│                  ",
				Big5:   []byte("\xa2x                  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x                  "),
			},
			{
				Utf8:   "  ▉      ▉     ███▉ ",
				Big5:   []byte("  \xa2p      \xa2p     \xa2i\xa2i\xa2i\xa2p "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[33m  \xa2p      \xa2p     \xa2i\xa2i\xa2i\xa2p "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 28
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2x"),
			},
			{
				Utf8:   "Attendance:  ",
				Big5:   []byte("Attendance:  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[37mAttendance:  "),
			},
			{
				Utf8:   "17794          ",
				Big5:   []byte("17794          "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[36m17794          "),
			},
			{
				Utf8:   "│                  ",
				Big5:   []byte("\xa2x                  "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x                  "),
			},
			{
				Utf8:   "  ▉      ▉     ▉    ▉ ",
				Big5:   []byte("  \xa2p      \xa2p     \xa2p    \xa2p "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[33m  \xa2p      \xa2p     \xa2p    \xa2p "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 29
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2x"),
			},
			{
				Utf8:   "Duration:    ",
				Big5:   []byte("Duration:    "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_WHITE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[37mDuration:    "),
			},
			{
				Utf8:   "2:16           ",
				Big5:   []byte("2:16           "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_CYAN, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[36m2:16           "),
			},
			{
				Utf8:   "│                 ",
				Big5:   []byte("\xa2x                 "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x                 "),
			},
			{
				Utf8:   " ███  ███   ███▉ ",
				Big5:   []byte(" \xa2i\xa2i\xa2i  \xa2i\xa2i\xa2i   \xa2i\xa2i\xa2i\xa2p "),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_YELLOW, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[33m \xa2i\xa2i\xa2i  \xa2i\xa2i\xa2i   \xa2i\xa2i\xa2i\xa2p "),
			},
			{
				Utf8:   "│",
				Big5:   []byte("\xa2x"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[34m\xa2x"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 30
			{
				Utf8:   "└═════╧════════╩══════════════════════┘",
				Big5:   []byte("\xa2|\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xed\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xe4\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xa2}"),
				Color0: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				Color1: types.Color{Foreground: types.COLOR_FOREGROUND_BLUE, Background: types.COLOR_BACKGROUND_BLACK, Highlight: true},
				DBCS:   []byte("\x1b[1;34m\xa2|\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xed\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xe4\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xf9\xa2}"),
			},
			{
				Utf8:   "",
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("\x1b[m"),
			},
		},
		{ // 31
		},
		{ // 32
			{
				Utf8:   "--",
				Big5:   []byte("--"),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("--"),
			},
		},
		{ // 33
			{
				Utf8:   "http://blog.xuite.net/baseballman/blog NBA每日線上高光 & 線上Top10",
				Big5:   []byte("http://blog.xuite.net/baseballman/blog NBA\xa8C\xa4\xe9\xbdu\xa4W\xb0\xaa\xa5\xfa & \xbdu\xa4WTop10"),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("http://blog.xuite.net/baseballman/blog NBA\xa8C\xa4\xe9\xbdu\xa4W\xb0\xaa\xa5\xfa & \xbdu\xa4WTop10"),
			},
		},
		{ // 34
		},
		{ // 35
			{
				Utf8:   "https://goo.gl/YGH7x7 Chrome extensions to Play Stream",
				Big5:   []byte("https://goo.gl/YGH7x7 Chrome extensions to Play Stream"),
				Color0: types.DefaultColor,
				Color1: types.DefaultColor,
				DBCS:   []byte("https://goo.gl/YGH7x7 Chrome extensions to Play Stream"),
			},
		},
	}

	testFirstComments21 = []*schema.Comment{}

	testFullFirstComments21 = []*schema.Comment{}

	testTheRestComments21 = []*schema.Comment{}
}
